//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputDetail
    {
        public int Id { get; set; }
        public int InputId { get; set; }
        public int ProductId { get; set; }
        public string Unit { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
        public string Note { get; set; }
    
        public virtual Input Input { get; set; }
        public virtual Product Product { get; set; }
    }
}
