//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string ProductName { get; set; }
        public decimal Input { get; set; }
        public decimal Output { get; set; }
        public decimal TotalQuantity { get; set; }
        public Nullable<decimal> OutputPrice { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
